[tool.ruff]
# Базовые настройки
line-length = 120
target-version = "py39"

# Включаемые правила
select = [
    "E",   # PEP 8 ошибки (стиль)
    "F",   # Pyflakes (синтаксис)
    "B",   # Логические ошибки
    "ANN", # Аннотации типов
    "D",   # Docstring
    "PTH", # Pathlib (вместо os.path)
    "RUF", # Специфичные для Ruff правила
]

# Игнорируемые правила
ignore = [
    "E501",  # Длина строки
    "D203",  # Конфликт правил docstring
    "D212",  # Конфликт правил docstring
    "RUF001", # Кириллица в строках
    "RUF002", # Кириллица в docstring
    "RUF003", # Кириллица в комментариях
]

# Настройки для конкретных правил
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # Игнорировать неиспользуемые импорты в __init__.py